apiVersion: v1
kind: ConfigMap
metadata:
  name: devboard-configmap
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER | quote }}
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB | quote }}
  PORT: {{ .Values.config.PORT | quote }}
