kind: ConfigMap
apiVersion: v1
metadata:
  name: devboard-configmap
  namespace: devboard-ns

data:
  POSTGRES_USER: devboard # plain text , no need to base64 encode
  POSTGRES_DB: devboard
  PORT: "8080"
