namespace: devboard-ns

frontend:
  image: trainwithshubham/devboard-frontend:latest
  replicas: 1
  containerPort: 4173
  service:
    type: NodePort
    port: 80
    nodePort: 30001
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

backend:
  image: trainwithshubham/devboard-backend:latest
  replicas: 1
  containerPort: 8080
  service:
    port: 8080
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

postgres:
  image: postgres:16-alpine
  storage: 0.5Gi
  pvHostPath: /mnt/pg-data
  pvStorage: 1Gi
  storageClassName: manual

config:
  POSTGRES_USER: devboard
  POSTGRES_DB: devboard
  PORT: "8080"

secrets:
  # base64 for "devboard" — replace for real environments, this is a demo password
  POSTGRES_PASSWORD: ZGV2Ym9hcmQ=
