kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: devboard-ns

spec:
  selector:
    app: devboard-fe

  ports:
    - protocol: TCP
      port: 80
      targetPort: 4173 # container port
      nodePort: 30001
  type: NodePort
