name: Docker Lint

on:
  workflow_call:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [backend, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate ${{ matrix.target }} Dockerfile
        continue-on-error: true
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.target }}/Dockerfile
